import React from "react";
import { useLocation } from "react-router-dom";
import "../styles/resumePreview.css";

const ResumePreview = () => {
  const location = useLocation();
  const { name, email, phone, experience } = location.state || {};

  return (
    <div className="resume-preview">
      <div className="resume-header">
        <h1>{name || "Your Name"}</h1>
        <p>{email || "youremail@example.com"} | {phone || "123-456-7890"}</p>
      </div>

      <div className="resume-section">
        <h2>Work Experience</h2>
        <p>{experience || "Describe your work experience here..."}</p>
      </div>

      <div className="resume-footer">
        <p>Generated by Resume Screening Tool</p>
      </div>
    </div>
  );
};

export default ResumePreview;
